// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WifiAuth.DB;

namespace WifiAuth.Migrations
{
    [DbContext(typeof(WifiAuthContext))]
    [Migration("20171216040735_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("WifiAuth.DB.DeviceLogEntry", b =>
                {
                    b.Property<int>("DeviceLogEntryID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("FirstSeen");

                    b.Property<string>("Login");

                    b.Property<string>("MACAddress");

                    b.HasKey("DeviceLogEntryID");

                    b.ToTable("DeviceLogEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
