// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WifiAuth.DB;

namespace WifiAuth.Migrations
{
    [DbContext(typeof(WifiAuthContext))]
    [Migration("20171218031817_UserOverride")]
    partial class UserOverride
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("WifiAuth.DB.DeviceLogEntry", b =>
                {
                    b.Property<int>("DeviceLogEntryID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("FirstSeen");

                    b.Property<string>("Login");

                    b.Property<string>("MACAddress");

                    b.HasKey("DeviceLogEntryID");

                    b.ToTable("DeviceLogEntries");
                });

            modelBuilder.Entity("WifiAuth.DB.UserOverride", b =>
                {
                    b.Property<string>("Login")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Override");

                    b.Property<string>("PasswordOverride");

                    b.HasKey("Login");

                    b.ToTable("UserOverrides");
                });
#pragma warning restore 612, 618
        }
    }
}
