// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WifiAuth.DB;

namespace WifiAuth.Migrations
{
    [DbContext(typeof(WifiAuthContext))]
    [Migration("20191225032258_Attendees")]
    partial class Attendees
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("WifiAuth.DB.Attendee", b =>
                {
                    b.Property<string>("BadgeID")
                        .HasColumnType("TEXT");

                    b.HasKey("BadgeID");

                    b.ToTable("Attendees");
                });

            modelBuilder.Entity("WifiAuth.DB.DeviceLogEntry", b =>
                {
                    b.Property<int>("DeviceLogEntryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .HasColumnType("TEXT");

                    b.Property<string>("MACAddress")
                        .HasColumnType("TEXT");

                    b.HasKey("DeviceLogEntryID");

                    b.ToTable("DeviceLogEntries");
                });

            modelBuilder.Entity("WifiAuth.DB.UserOverride", b =>
                {
                    b.Property<string>("Login")
                        .HasColumnType("TEXT");

                    b.Property<int>("Override")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordOverride")
                        .HasColumnType("TEXT");

                    b.HasKey("Login");

                    b.ToTable("UserOverrides");
                });
#pragma warning restore 612, 618
        }
    }
}
